### ISSUE TITLE
Can't use it with Climber Selection Bar

### ISSUE THREAD

**Issue by TFR92** [caallard/Watefall_for_dummies#1]
I can't use the chart with Climber Container.

I can save the chart as a master visualization, but when I add it to the Climber, the chart disappear.

![Climber](https://user-images.githubusercontent.com/52801201/61147820-b8521880-a4b3-11e9-8b54-5b74b2a76206.PNG)

**Comment by caallard** [comment]
Hello,
Are you in editing mode? Climber seems to not show the graph in editing mode (not for the waterfall & not for a simple table).

In normal mode, it seems to work for me:

![image](https://user-images.githubusercontent.com/18308168/61284681-c065cd00-a7bf-11e9-9077-04e56c5b1a5a.png)
